
spring.datasource.url=jdbc:mysql://localhost:3306/datn
spring.datasource.username=root
spring.datasource.password=Hoangthuha2804@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9000